"""Application settings, driven by environment variables (see .env.example)."""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path
from typing import Literal

from pydantic import model_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

# The project root (config.py -> podcast_compactor -> src -> repo). Persistence
# and the .env lookup anchor here rather than to the process working directory,
# so a run launched from any CWD (API server, worker, or an ad-hoc CLI run)
# shares one database and data dir — otherwise its jobs land in a private
# ./data/app.db the web UI never reads (issue #27).
_PROJECT_ROOT = Path(__file__).resolve().parents[2]


def _anchor(path: Path) -> Path:
    """Resolve a relative path against the project root, not the CWD."""
    return path if path.is_absolute() else (_PROJECT_ROOT / path).resolve()


def _anchor_sqlite_url(url: str) -> str:
    """Rewrite a relative sqlite file path to an absolute, project-anchored one.

    SQLAlchemy resolves ``sqlite:///./data/app.db`` against the process CWD at
    connect time, so the same URL points at different files depending on where
    the process started. Non-sqlite URLs, in-memory databases, and already
    absolute paths pass through unchanged.
    """
    prefix = "sqlite:///"
    if not url.startswith(prefix):
        return url
    tail = url[len(prefix) :]
    if not tail or tail.startswith("/") or tail.startswith(":memory:"):
        return url
    return f"{prefix}{_anchor(Path(tail))}"


class Settings(BaseSettings):
    """Runtime configuration. Every value can be overridden via env vars."""

    model_config = SettingsConfigDict(env_file=_PROJECT_ROOT / ".env", extra="ignore")

    # Secrets / connections
    anthropic_api_key: str | None = None
    database_url: str = "sqlite:///./data/app.db"
    redis_url: str = "redis://localhost:6379"

    # Storage
    data_dir: Path = Path("data")

    # Dependency selection: fakes keep the app runnable without GPU/network.
    use_fakes: bool = True

    # LLM backend selection. "anthropic" (default) uses the Claude API and needs
    # ANTHROPIC_API_KEY; "ollama" uses a local Ollama server and needs no key;
    # "openrouter" calls a hosted model on OpenRouter (OpenAI-compatible chat
    # completions) and reuses OPENROUTER_API_KEY / OPENROUTER_BASE_URL below.
    llm_backend: Literal["anthropic", "ollama", "openrouter"] = "anthropic"
    ollama_model: str = "qwen2.5-coder:7b"
    ollama_base_url: str = "http://localhost:11434"

    # TTS backend selection. "f5" (default) synthesizes locally on the GPU via
    # F5-TTS (cloned/reference voices) + Kokoro (stock voices). "openrouter" calls
    # a hosted model on OpenRouter's OpenAI-compatible /audio/speech endpoint — no
    # GPU needed — and needs OPENROUTER_API_KEY.
    tts_backend: Literal["f5", "openrouter"] = "f5"
    openrouter_api_key: str | None = None
    openrouter_tts_model: str = "fish-audio/s2.1-pro"
    openrouter_base_url: str = "https://openrouter.ai/api/v1"

    # OpenRouter LLM model used when LLM_BACKEND=openrouter. Must support tool /
    # function calling (langchain's structured-output method). Picked at runtime
    # from the Settings page; this is only the fallback default.
    openrouter_llm_model: str = "openai/gpt-4o-mini"

    # Models
    whisper_model: str = "large-v3"
    map_model: str = "claude-haiku-4-5-20251001"
    reduce_model: str = "claude-opus-4-8"

    # Scripting
    wpm: int = 130

    # Bundled default narrator voice (F5-TTS needs a reference clip + its text).
    narrator_ref_audio: Path | None = None
    narrator_ref_text: str | None = None

    # Two-host mode: reference clip + text for each stock host voice.
    host_a_ref_audio: Path | None = None
    host_a_ref_text: str | None = None
    host_b_ref_audio: Path | None = None
    host_b_ref_text: str | None = None

    # Stock (Kokoro catalog) voices: the fallback voice for a detected speaker that
    # isn't cloned and has no explicit assignment. See synth/stock_voices.py.
    default_stock_voice: str = "af_heart"

    # Opt-in voice cloning (Phase 3).
    clone_disclaimer: str = (
        "This episode was generated by AI. The voices are synthetic and are not the original hosts."
    )
    hf_token: str | None = None  # Hugging Face token for pyannote diarization
    # pyannote diarization pipeline (gated on HF; accept its license once). The
    # 4.x-native "community-1" pipeline returns per-speaker embeddings, which the
    # cross-episode speaker-identity clustering needs.
    diarization_model: str = "pyannote/speaker-diarization-community-1"
    # Cosine-distance threshold for merging same-speaker embeddings across
    # episodes. Lower = stricter (fewer merges). Tuned against pyannote embeddings.
    cross_episode_speaker_threshold: float = 0.70

    # Worker: a multi-episode diarized+cloned job runs whisper, pyannote, the LLM
    # and TTS back to back, well past arq's 300s default. Give it real headroom and
    # do not silently retry a heavy job that fails deterministically.
    job_timeout_seconds: int = 1800
    job_max_tries: int = 1

    # HTTP API
    api_token: str | None = None  # when set, all endpoints except /health require it
    cors_allow_origins: list[str] = ["*"]

    @model_validator(mode="after")
    def _anchor_persistence_to_project_root(self) -> Settings:
        """Make persistence locations independent of the process CWD (issue #27)."""
        self.data_dir = _anchor(self.data_dir)
        self.database_url = _anchor_sqlite_url(self.database_url)
        return self


@lru_cache
def get_settings() -> Settings:
    """Return a cached Settings instance."""
    return Settings()
