"""Application settings, driven by environment variables (see .env.example)."""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path
from typing import Literal

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    """Runtime configuration. Every value can be overridden via env vars."""

    model_config = SettingsConfigDict(env_file=".env", extra="ignore")

    # Secrets / connections
    anthropic_api_key: str | None = None
    database_url: str = "sqlite:///./data/app.db"
    redis_url: str = "redis://localhost:6379"

    # Storage
    data_dir: Path = Path("data")

    # Dependency selection: fakes keep the app runnable without GPU/network.
    use_fakes: bool = True

    # LLM backend selection. "anthropic" (default) uses the Claude API and needs
    # ANTHROPIC_API_KEY; "ollama" uses a local Ollama server and needs no key.
    llm_backend: Literal["anthropic", "ollama"] = "anthropic"
    ollama_model: str = "qwen2.5-coder:7b"
    ollama_base_url: str = "http://localhost:11434"

    # Models
    whisper_model: str = "large-v3"
    map_model: str = "claude-haiku-4-5-20251001"
    reduce_model: str = "claude-opus-4-8"

    # Scripting
    wpm: int = 130

    # Bundled default narrator voice (F5-TTS needs a reference clip + its text).
    narrator_ref_audio: Path | None = None
    narrator_ref_text: str | None = None

    # Two-host mode: reference clip + text for each stock host voice.
    host_a_ref_audio: Path | None = None
    host_a_ref_text: str | None = None
    host_b_ref_audio: Path | None = None
    host_b_ref_text: str | None = None

    # Stock (Kokoro catalog) voices: the fallback voice for a detected speaker that
    # isn't cloned and has no explicit assignment. See synth/stock_voices.py.
    default_stock_voice: str = "af_heart"

    # Opt-in voice cloning (Phase 3).
    clone_disclaimer: str = (
        "This episode was generated by AI. The voices are synthetic and are not "
        "the original hosts."
    )
    hf_token: str | None = None  # Hugging Face token for pyannote diarization

    # HTTP API
    api_token: str | None = None  # when set, all endpoints except /health require it
    cors_allow_origins: list[str] = ["*"]


@lru_cache
def get_settings() -> Settings:
    """Return a cached Settings instance."""
    return Settings()
