"""Output-language helpers for a digest (English default, Persian first extra).

This is the *spoken/written output* language of the digest — not the language
of the source podcast. Transcripts stay in the source language; script, arc,
chapters, show notes, and the cloning disclaimer follow the target language.
"""

from __future__ import annotations

from typing import Literal

TargetLanguage = Literal["en", "fa"]

SUPPORTED_LANGUAGES: tuple[TargetLanguage, ...] = ("en", "fa")

LANGUAGE_LABELS: dict[TargetLanguage, str] = {
    "en": "English",
    "fa": "Persian",
}

# Spoken-word rate used to size the script. Persian is space-tokenized like
# English, but native speech packs fewer space-separated tokens into a minute
# than English 130 WPM, so reusing 130 under-runs duration.
WPM_BY_LANGUAGE: dict[TargetLanguage, int] = {
    "en": 130,
    "fa": 110,
}

CLONE_DISCLAIMERS: dict[TargetLanguage, str] = {
    "en": (
        "This episode was generated by AI. The voices are synthetic and are not the original hosts."
    ),
    "fa": ("این قسمت توسط هوش مصنوعی ساخته شده است. صداها مصنوعی‌اند و صدای میزبان‌های اصلی نیستند."),
}

_ALIASES: dict[str, TargetLanguage] = {
    "en": "en",
    "eng": "en",
    "english": "en",
    "fa": "fa",
    "fas": "fa",
    "per": "fa",
    "persian": "fa",
    "farsi": "fa",
}


def normalize_language(value: str | None) -> TargetLanguage:
    """Return a canonical language code. Empty/None is English."""
    if value is None:
        return "en"
    key = value.strip().lower()
    if not key:
        return "en"
    if key not in _ALIASES:
        raise ValueError(
            f"unsupported target language {value!r}; choose from {list(SUPPORTED_LANGUAGES)}"
        )
    return _ALIASES[key]


def is_rtl(language: str) -> bool:
    return normalize_language(language) == "fa"


def wpm_for(language: str, fallback: int | None = None) -> int:
    lang = normalize_language(language)
    if lang == "en" and fallback is not None:
        return fallback
    return WPM_BY_LANGUAGE[lang]


def clone_disclaimer(language: str, fallback: str | None = None) -> str:
    lang = normalize_language(language)
    if lang == "en" and fallback:
        return fallback
    return CLONE_DISCLAIMERS[lang]


def language_instruction(language: str) -> str | None:
    """Prompt suffix asking the LLM to write structured output in `language`.

    English is the built-in default, so no extra instruction is appended.
    """
    lang = normalize_language(language)
    if lang == "en":
        return None
    return (
        "Write every field of your structured output in Persian (Farsi), using "
        "Persian script. Do not translate the result into English. Source "
        "transcripts and episode titles above may be in English — extract their "
        "meaning and write the digest in Persian."
    )
